# i-m-working-on-python-with-package-pyfits-can-i-solve-this-problem
Traceback (most recent call last):   File "phot.py", line 26, in &lt;module>     execfile('bib1.py')   File "bib1.py", line 9, in &lt;module>     import pyfits   File "/usr/lib64/python2.7/site-packages/pyfits/__init__.py", line 11, in &lt;module>     from . import core   File "/usr/lib64/python2.7/site-packages/pyfits/core.py", line 42, in &lt;module>     from . import convenience   File "/usr/lib64/python2.7/site-packages/pyfits/convenience.py", line 62, in &lt;module>     from .hdu.base import _BaseHDU, _ValidHDU   File "/usr/lib64/python2.7/site-packages/pyfits/hdu/__init__.py", line 3, in &lt;module>     from .compressed import CompImageHDU   File "/usr/lib64/python2.7/site-packages/pyfits/hdu/compressed.py", line 16, in &lt;module>     from ..fitsrec import FITS_rec   File "/usr/lib64/python2.7/site-packages/pyfits/fitsrec.py", line 18, in &lt;module>     from ._compat.weakref import WeakSet   File "/usr/lib64/python2.7/site-packages/pyfits/_compat/weakref.py", line 6, in &lt;module>     from ._weakset_py2 import WeakSet ImportError: No module named _weakset_py2
